# Generated by Django 3.0.7 on 2020-09-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaurabhComputerApp', '0002_auto_20200902_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
