# Generated by Django 3.0.7 on 2020-09-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaurabhComputerApp', '0006_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head1', models.CharField(default='', max_length=500)),
                ('chead1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('chead2', models.CharField(default='', max_length=5000)),
                ('sub_head', models.CharField(default='', max_length=500)),
                ('sub_chead', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
